language: node_js

node_js:
  - 8.9.0

cache:
  bundler: true
  yarn: true
  directories:
    - node_modules

before_script:
  - npm install

script:
  - npm run depoly

# deploy:
#   provider: pages
#   skip-cleanup: true
#   github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
#   keep-history: true
#   on:
#     branch: master
